/**
 * YOUR_GAME_NAME - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       YOUR_GAME_NAME
 *   Title ID:    0x00000000
 *   Base addr:   0x00010000
 *   Entry point: 0x00000000
 *   Code size:   ~??? KB (.text)
 *   Sections:    ?? (list them)
 *   Kernel imports: ??
 */

#include <windows.h>
#include <dbghelp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>
#include "recomp_icall_feedback.h"   /* no-op unless RECOMP_ICALL_FEEDBACK */
#include "lanceur.h"

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. The
 * host side then writes g_esp somewhere the generated code never reads, so the
 * guest starts with every register at zero and faults immediately, having
 * apparently ignored the setup that visibly ran. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
/* The indirect-call ring, declared here rather than by including
 * recomp_types.h: that header redefines eax, esi and the rest as macros over
 * these globals, which is exactly what this file must not have. Kept in step
 * with ICALL_TRACE_SIZE by hand -- it has been 16 since the ring existed. */
#define MAIN_ICALL_TRACE_SIZE 16
extern volatile uint32_t g_icall_trace[MAIN_ICALL_TRACE_SIZE];
extern volatile uint32_t g_icall_trace_idx;
/* x87 and SSE state. Global for the same reason the volatile GPRs are: one
 * guest routine can lift to several C functions, so a value written in one
 * body is read in the next. Defined in xbox_memory_layout.c like the rest of
 * the register file. */
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_ENTRY_POINT   0x001F6357  /* XBE entry point VA (DJFFNY, XDK 5849) */
#define YOUR_GAME_XBE_PATH      "game_files/default.xbe"
#define YOUR_GAME_DIR            "game_files"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Recompiled entry point (generated by recomp pipeline) */
extern void xbe_entry_point(void);

/* The flat dispatch table (recomp_dispatch.c, generated). */
extern int recomp_dispatch_init(void);

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
/* Name the guest function a fault happened in, and recover the call chain.
 *
 * Recompiled code faults as ordinary native code, so the exception record
 * carries a host RIP and nothing else -- there is no guest program counter to
 * report, and the host address changes every build. Two things recover the
 * guest view:
 *
 *   - every generated function is a real symbol in the image (sub_005A03C0
 *     and so on), so the linker's PDB already maps host address back to guest
 *     function. dbghelp turns an anonymous RIP into that name.
 *
 *   - every lifted call pushes its guest return address onto the guest stack
 *     before jumping, so the stack still holds the chain. Scanning up from esp
 *     for values inside the code sections recovers it.
 *
 * ponytail: the stack scan is a scan, not a frame walk -- these are FPO frames
 * with no reliable ebp chain, so there is nothing to walk. It over-reports,
 * since addresses from returned-from calls linger below esp, but naming the
 * guest function is the whole question at a fault.
 *
 * Requires linking dbghelp and keeping the .pdb beside the .exe.
 */
/* Sampling profiler, under RECOMP_PROFILE=<seconds between reports>.
 *
 * Every 2 ms each other thread of the process is suspended long enough to read
 * its instruction pointer. Nothing is resolved while a thread is suspended --
 * it may hold the heap lock that the symbol lookup needs -- so the addresses
 * are stored raw and named at report time. The report lists the functions
 * taking the most samples, per host thread: which is what decides whether the
 * time goes to the rasteriser, the vertex programs or the recompiled game. */
#include <tlhelp32.h>

enum { PROF_THREADS = 64, PROF_SAMPLES = 1 << 18 };
static struct { DWORD tid; uint64_t rip; } s_prof[PROF_SAMPLES];

static DWORD WINAPI profile_thread(LPVOID arg)
{
    DWORD every_ms = (DWORD)(uintptr_t)arg * 1000, self = GetCurrentThreadId();
    HANDLE th[PROF_THREADS];
    DWORD tids[PROF_THREADS];
    int nth = 0;
    ULONGLONG next_list = 0, next_report = GetTickCount64() + every_ms;
    size_t n = 0;

    for (;;) {
        ULONGLONG now = GetTickCount64();
        int i;

        if (now >= next_list) {
            HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);
            THREADENTRY32 te;
            for (i = 0; i < nth; i++)
                CloseHandle(th[i]);
            nth = 0;
            te.dwSize = sizeof te;
            if (snap != INVALID_HANDLE_VALUE && Thread32First(snap, &te)) {
                do {
                    if (te.th32OwnerProcessID != GetCurrentProcessId()
                        || te.th32ThreadID == self || nth == PROF_THREADS)
                        continue;
                    th[nth] = OpenThread(THREAD_SUSPEND_RESUME | THREAD_GET_CONTEXT,
                                         FALSE, te.th32ThreadID);
                    if (th[nth])
                        tids[nth++] = te.th32ThreadID;
                } while (Thread32Next(snap, &te));
            }
            if (snap != INVALID_HANDLE_VALUE)
                CloseHandle(snap);
            next_list = now + 500;
        }

        for (i = 0; i < nth && n < PROF_SAMPLES; i++) {
            CONTEXT c;
            if (SuspendThread(th[i]) == (DWORD)-1)
                continue;
            c.ContextFlags = CONTEXT_CONTROL;
            if (GetThreadContext(th[i], &c)) {
                s_prof[n].tid = tids[i];
                s_prof[n].rip = c.Rip;
                n++;
            }
            ResumeThread(th[i]);
        }

        if (now >= next_report) {
            /* Name each sample, then count (thread, function) pairs. */
            enum { SLOTS = 4096 };
            static struct { DWORD tid; uint64_t fn; unsigned hits; char name[64]; } agg[SLOTS];
            static struct { DWORD tid; unsigned hits; } per[PROF_THREADS * 2];
            unsigned used = 0, nper = 0, total = (unsigned)n;
            size_t k;
            char buf[sizeof(SYMBOL_INFO) + 128];
            SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;

            memset(agg, 0, sizeof agg);
            for (k = 0; k < n; k++) {
                DWORD64 disp = 0;
                uint64_t fn = s_prof[k].rip;
                const char *name = "?";
                unsigned j, h;
                memset(buf, 0, sizeof buf);
                sym->SizeOfStruct = sizeof(SYMBOL_INFO);
                sym->MaxNameLen = 127;
                if (SymFromAddr(GetCurrentProcess(), s_prof[k].rip, &disp, sym)) {
                    fn = sym->Address;
                    name = sym->Name;
                } else {
                    /* No symbol: name the module and the page, which still
                     * groups a function's samples and can be resolved later. */
                    static char alt[128];
                    HMODULE mod;
                    char path[MAX_PATH], *base;
                    static DWORD first_err;
                    if (!first_err) {
                        first_err = GetLastError();
                        fprintf(stderr, "[PROFILE] SymFromAddr failed, error %lu\n",
                                (unsigned long)first_err);
                    }
                    if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS
                                           | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                                           (LPCSTR)(uintptr_t)s_prof[k].rip, &mod)
                        && GetModuleFileNameA(mod, path, sizeof path)) {
                        base = strrchr(path, '\\');
                        fn = s_prof[k].rip & ~0xFFFull;
                        snprintf(alt, sizeof alt, "%s+0x%llX", base ? base + 1 : path,
                                 (unsigned long long)(fn - (uintptr_t)mod));
                        name = alt;
                    }
                }
                h = (unsigned)((fn * 2654435761u) ^ s_prof[k].tid) % SLOTS;
                for (j = 0; j < SLOTS; j++, h = (h + 1) % SLOTS) {
                    if (!agg[h].hits) {
                        agg[h].tid = s_prof[k].tid;
                        agg[h].fn = fn;
                        strncpy(agg[h].name, name, sizeof agg[h].name - 1);
                        used++;
                    }
                    if (agg[h].tid == s_prof[k].tid && agg[h].fn == fn) {
                        agg[h].hits++;
                        break;
                    }
                }
                for (j = 0; j < nper && per[j].tid != s_prof[k].tid; j++)
                    ;
                if (j == nper && nper < PROF_THREADS * 2)
                    per[nper++].tid = s_prof[k].tid;
                if (j < nper)
                    per[j].hits++;
            }
            fprintf(stderr, "[PROFILE] %u samples over %us, %u threads, %u distinct functions\n",
                    total, every_ms / 1000, nper, used);
            /* Busiest (thread, function) pairs; idle waits show up as
             * ntdll/kernel wait functions and read as such. */
            for (k = 0; k < 30; k++) {
                unsigned best = SLOTS, j;
                for (j = 0; j < SLOTS; j++)
                    if (agg[j].hits && (best == SLOTS || agg[j].hits > agg[best].hits))
                        best = j;
                if (best == SLOTS)
                    break;
                if (strstr(agg[best].name, "Wait") || strstr(agg[best].name, "Delay")
                    || strstr(agg[best].name, "Alert")) {
                    agg[best].hits = 0;
                    k--;
                    continue;
                }
                /* Share of one thread's time: every thread is sampled
                 * equally often, so total / nper samples make one thread. */
                fprintf(stderr, "[PROFILE] %5.1f%% of a thread  tid %5lu  %s\n",
                        100.0 * agg[best].hits * nper / (total ? total : 1),
                        (unsigned long)agg[best].tid, agg[best].name);
                agg[best].hits = 0;
            }
            fflush(stderr);
            n = 0;
            next_report = GetTickCount64() + every_ms;
        }
        Sleep(2);
    }
}

static void profile_start(void)
{
    const char *s = getenv("RECOMP_PROFILE");
    if (s && atoi(s) > 0) {
        HANDLE t = CreateThread(NULL, 0, profile_thread, (LPVOID)(uintptr_t)atoi(s), 0, NULL);
        if (t) {
            SetThreadPriority(t, THREAD_PRIORITY_TIME_CRITICAL);
            CloseHandle(t);
        }
    }
}

/* File and line for a host address, when the PDB carries them. */
static void print_source_line(DWORD64 addr)
{
    IMAGEHLP_LINE64 line;
    DWORD line_disp = 0;

    memset(&line, 0, sizeof line);
    line.SizeOfStruct = sizeof line;
    if (SymGetLineFromAddr64(GetCurrentProcess(), addr, &line_disp, &line))
        fprintf(stderr, "     %s:%lu\n", line.FileName,
                (unsigned long)line.LineNumber);
}

static void print_guest_context(void *rip)
{
    /* SYMBOL_INFO is variable-length: the name is written past the struct, so
     * it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n",
                sym->Name, (unsigned long long)disp);

    /* The +0x... above is a HOST offset and says nothing about which guest
     * instruction faulted. The source line does: the generated C carries a
     * `loc_XXXXXXXX:` label per basic block, so the file and line name the
     * guest address directly. Worth the two extra calls at fault time. */
    print_source_line((DWORD64)(uintptr_t)rip);

    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (return addresses, innermost first):\n");
        for (i = 0; i < 4096 && shown < 40; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
    }
}

/* Emulated MCPX APU (xbox_apu, from xemu). g_apu_state is defined by
 * src/apu/apu_mmio_hook.c and consulted by apu_hook_handle_mmio(); the host
 * creates the state and routes the faults, which is what these two do. The
 * APU's 512K register window is only unmapped (and so only faults) when
 * RECOMP_AC97_READY is set -- see xbox_memory_layout.c. */
extern MCPXAPUState *g_apu_state;
extern bool apu_hook_handle_mmio(PCONTEXT ctx, uintptr_t fault_addr,
                                 uint32_t fault_xbox_va, int is_write);
#define APU_MMIO_LO 0xFE800000u
#define APU_MMIO_HI 0xFE880000u

/* The USB host controllers XAPI drives directly to find the gamepad. Off
 * unless RECOMP_USB is set, in which case xbox_OhciInit makes their register
 * blocks fault so the accesses can be answered here. RECOMP_USB_TRACE says
 * whether the title's own driver ever looks. */
extern void xbox_OhciInit(void);
extern int  xbox_OhciOwnsAddress(uint32_t xbox_va);
extern int  xbox_OhciHandleMmio(void *ctx, uint32_t xbox_va);
extern void xbox_OhciReport(void);

/* Write watch, under RECOMP_WATCH_VA=<hex guest address>.
 *
 * The page holding the address is made read-only in the RAM view and in each
 * of its wrap mirrors (guest +64 MB steps), so a write through any of them
 * faults. The handler names the writer when the watched 4 bytes are hit, then
 * lets the write through by unprotecting and single-stepping, and protects the
 * page again on the step. Writes to the rest of the page are let through the
 * same way without a report. */
static uint32_t g_watch_va;
static DWORD    g_watch_old = PAGE_READWRITE;
enum { WATCH_VIEWS = 8 };

static void watch_protect(DWORD prot)
{
    uint32_t page = g_watch_va & ~0xFFFu;
    for (unsigned k = 0; k < WATCH_VIEWS; k++) {
        DWORD old;
        VirtualProtect((LPVOID)((uintptr_t)g_xbox_mem_offset + page + k * 0x04000000u),
                       0x1000, prot, &old);
    }
}

static int watch_page_of(uint32_t va)
{
    if (!g_watch_va)
        return 0;
    for (unsigned k = 0; k < WATCH_VIEWS; k++)
        if (((va - k * 0x04000000u) & ~0xFFFu) == (g_watch_va & ~0xFFFu))
            return 1;
    return 0;
}

/* The icall dump is written at exit and on a crash. A run that is simply
 * killed -- the feedback loop's timeout -- does neither, so it is also
 * rewritten every ten seconds. */
static DWORD WINAPI icall_dump_thread(LPVOID unused)
{
    (void)unused;
    for (;;) {
        Sleep(10000);
        RECOMP_ICALL_FEEDBACK_DUMP();
    }
}

static void watch_init(void)
{
    const char *s = getenv("RECOMP_WATCH_VA");
    if (!s)
        return;
    g_watch_va = (uint32_t)strtoul(s, NULL, 16);
    fprintf(stderr, "[WATCH] write watch on 0x%08X (value 0x%08X)\n",
            g_watch_va, *(uint32_t *)((uintptr_t)g_xbox_mem_offset + g_watch_va));
    watch_protect(PAGE_READONLY);
}

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_SINGLE_STEP && g_watch_va) {
        watch_protect(PAGE_READONLY);
        return EXCEPTION_CONTINUE_EXECUTION;
    }
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];
        uint32_t fault_va = (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);

        if (ep->ExceptionRecord->ExceptionInformation[0] == 1 && watch_page_of(fault_va)) {
            uint32_t off = (fault_va - g_watch_va) % 0x04000000u;
            if (off < 4 || off > 0xFFFFFFF0u) {
                fprintf(stderr, "[WATCH] write to 0x%08X (via 0x%08X) at RIP=0x%llX\n",
                        g_watch_va, fault_va, (unsigned long long)ep->ContextRecord->Rip);
                fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X"
                        " ebx=0x%08X esi=0x%08X edi=0x%08X\n",
                        g_eax, g_ecx, g_edx, g_esp, g_ebx, g_esi, g_edi);
                print_guest_context((void *)ep->ContextRecord->Rip);
            }
            watch_protect(PAGE_READWRITE);
            ep->ContextRecord->EFlags |= 0x100;   /* trap after the write */
            return EXCEPTION_CONTINUE_EXECUTION;
        }

        /* DirectSound (the XDK library linked into the title) programs the
         * APU through these registers. Decode the instruction, perform the
         * access on the emulated APU, and resume after it. */
        if (fault_va >= APU_MMIO_LO && fault_va < APU_MMIO_HI) {
            int is_write = ep->ExceptionRecord->ExceptionInformation[0] ? 1 : 0;
            if (apu_hook_handle_mmio(ep->ContextRecord, fault_addr, fault_va, is_write))
                return EXCEPTION_CONTINUE_EXECUTION;
        }

        /* USB host controller registers, when the model is on. */
        if (xbox_OhciOwnsAddress(fault_va)
            && xbox_OhciHandleMmio(ep->ContextRecord, fault_va))
            return EXCEPTION_CONTINUE_EXECUTION;

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));

        /* The last indirect-call targets, newest first. When a preserved
         * register comes back wrong, the callee that broke it is almost
         * always one of these -- and an indirect call is the one kind the
         * host call chain cannot name, because the frame is already gone. */
        {
            uint32_t idx = g_icall_trace_idx;
            int i;
            fprintf(stderr, "  last indirect-call targets (newest first):\n   ");
            for (i = 1; i <= MAIN_ICALL_TRACE_SIZE; i++)
                fprintf(stderr, " 0x%08X",
                        g_icall_trace[(idx - (uint32_t)i)
                                      & (MAIN_ICALL_TRACE_SIZE - 1)]);
            fprintf(stderr, "\n");
        }

        print_guest_context((void *)ep->ContextRecord->Rip);

        /* The host call chain: every generated function is a native frame,
         * so this names the guest callers even when the guest stack scan
         * finds nothing (a big frame, or a stack in a heap block). */
        {
            CONTEXT c = *ep->ContextRecord;
            STACKFRAME64 f;
            char sbuf[sizeof(SYMBOL_INFO) + 128];
            SYMBOL_INFO *sym = (SYMBOL_INFO *)sbuf;
            int depth;
            memset(&f, 0, sizeof f);
            f.AddrPC.Offset = c.Rip;    f.AddrPC.Mode = AddrModeFlat;
            f.AddrFrame.Offset = c.Rbp; f.AddrFrame.Mode = AddrModeFlat;
            f.AddrStack.Offset = c.Rsp; f.AddrStack.Mode = AddrModeFlat;
            fprintf(stderr, "  host call chain:\n");
            for (depth = 0; depth < 24; depth++) {
                DWORD64 disp = 0;
                if (!StackWalk64(IMAGE_FILE_MACHINE_AMD64, GetCurrentProcess(),
                                 GetCurrentThread(), &f, &c, NULL,
                                 SymFunctionTableAccess64, SymGetModuleBase64, NULL))
                    break;
                memset(sbuf, 0, sizeof sbuf);
                sym->SizeOfStruct = sizeof(SYMBOL_INFO);
                sym->MaxNameLen = 127;
                if (SymFromAddr(GetCurrentProcess(), f.AddrPC.Offset, &disp, sym)) {
                    fprintf(stderr, "    %s+0x%llX\n", sym->Name, (unsigned long long)disp);
                    print_source_line(f.AddrPC.Offset);
                }
            }
        }

        /* A title that dies mid-boot is exactly the one whose indirect-branch
         * targets we want: dump them before the process goes away. */
        RECOMP_ICALL_FEEDBACK_DUMP();

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* The launcher first: the game folder, the log, the settings window and
     * the RECOMP_* variables everything below reads (point 141). */
    if (!lanceur_run())
        return 0;

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== Def Jam - Static Recompilation ===\n");
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    /* Load symbols up front rather than from inside the handler: at fault
     * time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler prints no name. */
    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME | SYMOPT_LOAD_LINES);
    SymInitialize(GetCurrentProcess(), NULL, TRUE);
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, NULL);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over the
     * whole function table -- roughly log2(n) branches on *every*
     * indirect call, which for a 45,000-function C++ title is about 16
     * every time the game goes through a vtable. Half-Life 2 spent most
     * of its static initialisation inside recomp_lookup for exactly this
     * reason, and it read as a hang.
     *
     * Optional by design: if the allocation fails the search still works,
     * so a failure is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    /* Arm the hang watchdog. Does nothing unless RECOMP_WATCHDOG_SECS is set,
     * and must be called from this thread -- the guest registers it samples are
     * thread-local, so it has to be handed the copies belonging to the thread
     * that runs guest code.
     *
     * Not optional boilerplate: without this call RECOMP_WATCHDOG_SECS is
     * silently inert, and the one diagnostic that tells a hang from slowness
     * does nothing while appearing to be set. */
    xbox_WatchdogStart();

    /* The certificate only says "DJFFNY"; the window title gets the full name. */
    {
        extern void xbox_FramebufferWindowSetName(const char *utf8);
        xbox_FramebufferWindowSetName("Def Jam: Fight for NY");
    }

    /* GPU completion fence (Def Jam: Fight for NY, D3D8 XDK 5849).
     *
     * The D3D device struct lives at 0x00234770 and its pointer at 0x00234768
     * (D3D section BSS). Every pushbuffer kick (sub_0021EC50) spins until
     *     MEM32(MEM32(dev + 0x30))  >=  MEM32(dev + 0x2C) - requested
     * where +0x2C is the write-sequence counter and +0x30 points at the word
     * the GPU writes through NV097_BACK_END_WRITE_SEMAPHORE_RELEASE
     * (0x81202000, contiguous memory just below the pushbuffer ring). With no
     * GPU the word never moves and the main thread hangs on the first kick
     * after device creation. The NV2A poll thread mirrors the sequence
     * counter into it instead, which is what a GPU that finished everything
     * it was given would have written. Values from RECOMP_PEEK at the hang. */
    xbox_Nv2aMirrorFence(0x00234768, 0x2C, 0x30);

    /* Emulated APU, fed the base of guest physical RAM (guest VA 0 is native
     * g_xbox_mem_offset). Harmless when the register window is plain memory;
     * with RECOMP_AC97_READY set it answers DirectSound's register traffic. */
    g_apu_state = mcpx_apu_init_standalone((uint8_t *)(uintptr_t)g_xbox_mem_offset);
    if (!g_apu_state)
        fprintf(stderr, "[BOOT] APU emulation unavailable\n");

    /* USB host controllers. No-op unless RECOMP_USB is set. */
    xbox_OhciInit();

    profile_start();

    /* Register the atexit() dump of observed indirect-branch targets. */
    watch_init();
    RECOMP_ICALL_FEEDBACK_INIT();
    CloseHandle(CreateThread(NULL, 0, icall_dump_thread, NULL, 0, NULL));

    /* L'ecran large cote front end (RECOMP_WIDESCREEN).
     *
     * Le front end Flash lit une variable externe gWidescreenMode et en tire
     * son global WIDESCREEN : les deux films principaux (screens/main.big et
     * mainBE.big) portent la chaine dans leur pool de constantes, juste a
     * cote de "1" et de "WIDESCREEN". Le titre, lui, pousse la valeur "off",
     * ecrite en dur : sub_0006B760 appelle sub_00068850("gWidescreenMode",
     * 0x0029A9D4), et cette adresse est le seul endroit du XBE ou la chaine
     * est referencee. sub_00068850 *recopie* la valeur dans sa table, donc le
     * changement doit arriver avant que le front end s'initialise : ici.
     *
     * RECOMP_WIDESCREEN_FE donne une autre valeur ("on", "true"...) sans
     * reconstruire, et une valeur vide laisse le titre tranquille : quelle
     * valeur le film attend reste a verifier en jeu. */
    {
        const char *ws = getenv("RECOMP_WIDESCREEN");
        if (ws && *ws && *ws != '0' && g_xbox_mem_offset) {
            const char *val = getenv("RECOMP_WIDESCREEN_FE");
            if (!val) val = "1";
            if (*val) {
                char *dst = (char *)((uintptr_t)g_xbox_mem_offset + 0x0029A9D4u);
                size_t n = strlen(val);
                if (n > 3) n = 3;            /* la place de "off" : trois caracteres */
                memcpy(dst, val, n);
                dst[n] = 0;
                fprintf(stderr, "  [16:9] gWidescreenMode = \"%s\" pour le front end\n",
                        dst);
            }
        }
    }

    /* Le dossier mods : les coreID clones (point 105 de GUIDE_FR.md).
     *
     * Tout ce qu'un coreID porte vit dans des fichiers que le dossier mods
     * sait remplacer -- animations wres<N>, IA char<N>.xml, table de coups et
     * Blazin dans main_all.dat --, sauf la voix : elle vient d'une table de
     * l'executable, 104 entrees de 12 octets a 0x2DC5D0 (voix, trois octets,
     * -1), lue par FUN_0003e170 au lancement de chaque combat. Mesure : l'entree
     * n donne la voix du coreID n sur six combattants.
     *
     * game_files\mods\coreid.txt : une ligne par coreID clone,
     *     <coreID> <donneur> <voix>
     * L'entree <coreID> recoit les 12 octets de celle du donneur, puis la voix
     * donnee. Ecrit par outils\coreid.py. RECOMP_MODS=0 l'ignore. */
    {
        const char *m = getenv("RECOMP_MODS");
        FILE *f = (m && *m == '0') ? NULL : fopen(YOUR_GAME_DIR "/mods/coreid.txt", "r");
        if (f && g_xbox_mem_offset) {
            uint8_t *table = (uint8_t *)((uintptr_t)g_xbox_mem_offset + 0x002DC5D0u);
            char line[256];
            while (fgets(line, sizeof line, f)) {
                int core, donor, voice;
                if (line[0] == '#' || sscanf(line, "%d %d %d", &core, &donor, &voice) != 3)
                    continue;
                if (core < 0 || core > 103 || donor < 0 || donor > 103) {
                    fprintf(stderr, "  [MODS] coreid.txt : %d ou %d hors de la table (0 a 103)\n",
                            core, donor);
                    continue;
                }
                memmove(table + 12 * core, table + 12 * donor, 12);
                memcpy(table + 12 * core, &voice, 4);
                fprintf(stderr, "  [MODS] coreID %d : entree de %d, voix %d\n", core, donor, voice);
            }
        }
        if (f)
            fclose(f);
    }

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
